export const newBorders = {
    "AD": ["FR", "ES"],
    "AE": ["OM", "QA", "SA", "IR"],
    "AF": ["PK", "IR", "TM", "UZ", "TJ", "CN"],
    "AL": ["GR", "MK", "RS", "ME", "IT"],
    "AM": ["IR", "AZ", "TR", "GE"],
    "AO": ["NA", "ZM", "CD", "CG"],
    "AR": ["CL", "UY", "BR", "PY", "BO"],
    "AT": ["DE", "CZ", "SK", "HU", "SI", "IT", "CH"],
    "AU": ["NZ", "PG", "ID"],
    "AZ": ["IR", "AM", "GE", "RU"],
    "BA": ["RS", "HR", "ME"],
    "BD": ["IN", "MM"],
    "BE": ["BG", "FR", "NL", "DE", "LU"],
    "BF": ["ML", "NE", "CI", "GH", "TG", "BJ"],
    "BG": ["TR", "MK", "RS", "RO", "GR"],
    "BH": ["QA", "SA", "IR"],
    "BI": ["TZ", "CD", "RW"],
    "BJ": ["NG", "TG", "BF", "NE"],
    "BN": ["MY"],
    "BO": ["PE", "CL", "BR", "PY", "AR"],
    "BR": ["GF", "SR", "GY", "VE", "CO", "PE", "BO", "PY", "AR", "UY"],
    "BS": ["US", "CU", "HT", "DO"],
    "BT": ["CN", "IN"],
    "BW": ["ZA", "NA", "ZW"],
    "BY": ["RU", "UA", "PL", "LT", "LV"],
    "BZ": ["MX", "GT", "HN"],
    "CA": ["US", "GL"],
    "CD": ["CG", "CF", "SS", "UG", "RW", "BI", "TZ", "ZM", "AO"],
    "CF": ["TD", "SD", "SS", "CD", "CG", "CM"],
    "CG": ["CM", "CF", "CD", "AO", "GA"],
    "CH": ["AT", "IT", "FR", "DE"],
    "CI": ["GH", "BF", "ML", "GN", "LR"],
    "CL": ["AR", "BO", "PE"],
    "CM": ["GQ", "NG", "TD", "CF", "CG", "GA"],
    "CN": ["KP", "RU", "MN", "KZ", "KG", "TJ", "AF", "PK", "IN", "NP", "BT", "MM", "VN", "LA"],
    "CO": ["PA", "VE", "BR", "EC", "PE"],
    "CR": ["PA", "NI"],
    "CU": ["US", "BS", "JM", "HT"],
    "CY": ["TR", "SY", "LB"],
    "CZ": ["DE", "PL", "SK", "AT"],
    "DE": ["DK", "SE", "PL", "CZ", "AT", "CH", "FR", "BE", "LU", "NL"],
    "DJ": ["YE", "ER", "ET", "SO"],
    "DK": ["NO", "SE", "DE"],
    "DO": ["HT", "PR"],
    "DZ": ["TN", "LY", "NE", "ML", "MR", "EH", "MA"],
    "EC": ["CO", "PE"],
    "EE": ["FI", "RU", "LV"],
    "EG": ["IL", "SA", "LY", "SD", "SA", "JO"],
    "EH": ["MA", "DZ", "MR"],
    "ER": ["YE", "DJ", "ET", "SD"],
    "ES": ["MA", "PT", "FR"],
    "ET": ["SO", "DJ", "ER", "KE", "SS", "SD"],
    "FI": ["RU", "EE", "SE", "NO"],
    "FK": ["AR", "CL"],
    "FR": ["BE", "LU", "DE", "CH", "IT", "ES", "GB"],
    "GA": ["CG", "GQ", "CM"],
    "GB": ["IE", "FR", "BE", "NL", "IS"],
    "GE": ["RU", "AZ", "AM", "TR"],
    "GF": ["BR", "SR"],
    "GH": ["TG", "BF", "CI"],
    "GL": ["CA","IS"],
    "GM": ["SN"],
    "GN": ["SN", "GW", "ML", "CI", "LR", "SL"],
    "GQ": ["GA", "CM"],
    "GR": ["TR", "BG", "MK", "AL"],
    "GT": ["MX", "BZ", "HN", "SV"],
    "GW": ["GN", "SN"],
    "GY": ["SR", "BR", "VE"],
    "HN": ["NI", "SV", "GT"],
    "HR": ["BA", "RS", "HU", "SI", "IT"],
    "HT": ["DO", "CU", "JM"],
    "HU": ["SK", "UA", "RO", "RS", "HR", "SI", "AT"],
    "ID": ["PG", "AU", "MY", "PH"],
    "IE": ["GB", "IS"],
    "IL": ["EG", "PS", "LB", "SY", "JO"],
    "IN": ["LK", "MM", "BD", "BT", "CN", "NP", "PK"],
    "IQ": ["IR", "TR", "SY", "JO", "SA", "KW"],
    "IR": ["TM", "AF", "PK", "AE", "QA", "BH"],
    "IS": ["GL", "GB", "IE"],
    "IT": ["FR", "CH", "AT", "SI", "HR", "AL"],
    "JM": ["HT", "CU"],
    "JO": ["IL", "PS", "SY", "IQ", "SA"],
    "JP": ["RU", "KP", "KR"],
    "KE": ["SO", "ET", "SS", "UG", "TZ"],
    "KG": ["KZ", "CN", "TJ", "UZ"],
    "KH": ["VN", "LA", "TH"],
    "KP": ["RU", "CN", "KR", "KP"],
    "KR": ["JP", "KP"],
    "KW": ["IR", "IQ", "SA"],
    "KZ": ["RU", "CN", "KG", "UZ", "TM"],
    "LA": ["CN", "VN", "KH", "TH", "MM"],
    "LB": ["SY", "JO", "IL", "CY"],
    "LI": ["AT", "CH"],
    "LK": ["IN"],
    "LR": ["CI", "GN", "SL"],
    "LS": ["ZA"],
    "LT": ["LV", "BY", "PL"],
    "LU": ["DE", "FR", "BE"],
    "LV": ["EE", "RU", "BY", "LT"],
    "LY": [],
    "MA": [],
    "MC": [],
    "MD": [],
    "ME": [],
    "MF": [],
    "MG": [],
    "MH": [],
    "MK": [],
    "ML": [],
    "MM": [],
    "MN": [],
    "MO": [],
    "MP": [],
    "MQ": [],
    "MR": [],
    "MS": [],
    "MT": [],
    "MU": [],
    "MV": [],
    "MW": [],
    "MX": [],
    "MY": [],
    "MZ": [],
    "NA": [],
    "NC": [],
    "NE": [],
    "NF": [],
    "NG": [],
    "NI": [],
    "NL": [],
    "NO": [],
    "NP": [],
    "NR": [],
    "NU": [],
    "NZ": [],
    "OM": [],
    "PA": [],
    "PE": [],
    "PF": [],
    "PG": [],
    "PH": [],
    "PK": [],
    "PL": [],
    "PM": [],
    "PN": [],
    "PR": [],
    "PS": [],
    "PT": [],
    "PW": [],
    "PY": [],
    "QA": [],
    "RE": [],
    "RO": [],
    "RS": [],
    "RU": [],
    "RW": [],
    "SA": [],
    "SB": [],
    "SC": [],
    "SD": [],
    "SE": [],
    "SG": [],
    "SH": [],
    "SI": [],
    "SJ": [],
    "SK": [],
    "SL": [],
    "SM": [],
    "SN": [],
    "SO": [],
    "SR": [],
    "SS": [],
    "ST": [],
    "SV": [],
    "SX": [],
    "SY": [],
    "SZ": [],
    "TC": [],
    "TD": [],
    "TF": [],
    "TG": [],
    "TH": [],
    "TJ": [],
    "TK": [],
    "TL": [],
    "TM": [],
    "TN": [],
    "TO": [],
    "TR": [],
    "TT": [],
    "TV": [],
    "TW": [],
    "TZ": [],
    "UA": [],
    "UG": [],
    "UM": [],
    "US": [],
    "UY": [],
    "UZ": [],
    "VA": [],
    "VC": [],
    "VE": [],
    "VG": [],
    "VI": [],
    "VN": [],
    "VU": [],
    "WF": [],
    "WS": [],
    "XK": [],
    "YE": [],
    "YT": [],
    "ZA": [],
    "ZM": [],
    "ZW": [],
}